name: foreign

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      token_input:
        required: true
        type: string
    secrets:
      token:
        required: true
        
jobs:
  my-real-job:
    name: my real job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo hello ${{ inputs.username }}:${{ secrets.token }}:${{ inputs.token_input }}
        name: my step
      - run: ls 
